### ISSUE TITLE
Price as Money?

### ISSUE THREAD

**Issue by ericroberts** [crowdint/acts_as_shopping_cart#12]
Why not use the money gem or similar so that currency can be handled correctly in the cart?

**Comment by imshenitsky** [comment]
how to get it to work?
```
Bundler could not find compatible versions for gem "money-rails":
  In Gemfile:
    acts_as_shopping_cart (>= 0) ruby depends on
      money-rails (~> 0.12.0) ruby

    money-rails (1.2.0)
```j

**Comment by dabit** [comment]
Looks like newer versions of Money broke the feature and they pulled out older versions. I'll fix and merge as soon as I can.

**Comment by dabit** [comment]
Version 0.3.0 has been released with Money support. Please try it and report a new issue if you find any trouble.
