### ISSUE TITLE
ShoppingCart has_many products through ShoppingCartItem

### ISSUE THREAD

**Issue by mcmegavolt** [crowdint/acts_as_shopping_cart#18]
How to get a collection of products like **ShoppingCart.products**?
Is it possible?

**Comment by tk5446** [comment]
thanks. I ended up implementing this way to avoid multiple calls to db. 

def products
  Product.find(shopping_cart_items.collect(&:item_id))
end

Of course this works for me because only holding object of Product class in ShoppingCart right now
